### ISSUE TITLE
NFT Marketplace: contract and limitations questions

### ISSUE THREAD

**Issue by web3cub** [OpenZeppelin/workshops#19]
Hi all,

I'm not currently building a marketplace yet, but very keen to better understand some of the concepts and best practices.

Let's say I want to build a marketplace that only shows the items that are created and minted there, not like OpenSea where you can see pretty much everything anyone owns in the currently active chain.

The tokens would be single items with one or multiple editions. Support for generative collections with thousands of unique tokens is not needed.

I've been looking at this workshop but a couple of things are not very clear to me yet:

1. what kind of contract would be ideal for this purpose with lazy minting
2. should we use just a single contract for everything that will be ever minted through the platform
3. related to item 2; what are the limits of tokens a contract can store

These are just some initial thoughts and nothing is built up yet.

Thanks all!

**Comment by nshCore** [comment]
For a good marketplace base you can checkout https://github.com/ourzora/auction-house

although you should separate the concept of marketplace and minting, this workshop can guide you through lazy minting https://github.com/OpenZeppelin/workshops/tree/master/06-nft-merkle-drop

**Comment by mverzilli** [comment]
Thanks @web3cub and @nshCore for your contributions! @web3cub, I think the right place for these sort of questions is our forum (https://forum.openzeppelin.com/)

Please direct your question there, where you'll get a much bigger audience :).

Closing this issue,
