### ISSUE TITLE
signer.js is empty?

### ISSUE THREAD

**Issue by elranu** [OpenZeppelin/workshops#3]
Hi, 
I´m having compilation issues with this file. https://github.com/OpenZeppelin/workshops/blob/master/01-defender-meta-txs/app/src/eth/signer.js

```
./src/eth/signer.js
SyntaxError: C:\Dev\repos\workshops-Oz\01-defender-meta-txs\app\src\eth\signer.js: Unexpected token (1:0)

> 1 | ../../../src/signer.js
    | ^
```

Any idea? Did I miss some step?

**Comment by abcoathup** [comment]
Hi @elranu,

I ran the workshop code on WSL2 (Window Subsystem for Linux) on Windows 10.  I haven't tested just on Windows 10.

You may want to try using WSL2.

**Comment by elranu** [comment]
Yes, on WSL2 works good. Thanks.

**Comment by abcoathup** [comment]
Hi @elranu,

Glad to hear that WSL2 solved the issue.  I recommend using WSL2 as much of the ecosystem was developed for and tested on Linux.
