### ISSUE TITLE
forwarder.getNonce is not a function

### ISSUE THREAD

**Issue by burhon97** [OpenZeppelin/workshops#41]
I have tried your example `workshops/25-defender-metatx-api` and on running script `scripts/sign.js` got error: 

```bash
Signing registration of alice as 0xA7C37aEfF34ac0994B3a350c56a591f321EbD8A3...
TypeError: forwarder.getNonce is not a function
```

Please help me to resolve this issue!

**Comment by ElerianDePenaFuerte** [comment]
getNonce was used in the old OZ contracts V4. I assume you are using V5 of the contracts. Thus replace getNonce() by nonces()

**Comment by burhon97** [comment]
thanks @ElerianDePenaFuerte
